import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";
import Button from "@/components/Button/Button";
import Sidebar from "@/components/Sidebar/Sidebar";
import { device } from "@/constants/devices";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chinmoy C Pradhan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Sidebar />
          <Main>
            <Title>
              Hi&#44; <br /> I&apos;m Chinmoy&#44; <br />
              Fullstack developer
            </Title>
            <p className={styles.description}>
              Connect with me{" "}
              <Button link="https://www.linkedin.com/in/chinmoypradhan/">
                Linkedin
              </Button>
            </p>
          </Main>
      </Container>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const Container = styled.div`
  display: flex;
  justify-content: space-between;
`;
const Main = styled.div`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  margin-left: 2rem;
  @media ${device.tablet} {
    margin-left: 0rem;
  }
`
const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  text-align: left;
  @media ${device.laptop} {
    font-size: 4rem;
  }
`;
